<?php 
	$nav = 'about';
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php include($_SERVER['DOCUMENT_ROOT'] . '/includes/head.php'); ?>
	<title><?php print($site_title); ?> | About</title>
	
	<script src="/js/inside.js" type="text/javascript"></script>

</head>
<body id="body_about" class="inside_body">
	<div id="inside_wrapper"><div id="main_inside">
		<?php include($_SERVER['DOCUMENT_ROOT'] . '/includes/nav.php'); ?>
		<h2>About Chuck</h2>
		<div class="intro">
			<p><a href="https://s3-us-west-1.amazonaws.com/chuckharper/images/chuck_apple2.jpg" rel="shadowbox[Mixed];width=480;height=480" class="leading_image"><img src="https://s3-us-west-1.amazonaws.com/chuckharper/images/chuck_apple2_thumb.jpg" alt="Chuck with Apple IIe in February, 1987" title="Chuck with Apple IIe in February, 1987" /></a>In 1984 my father purchased an Apple IIe computer with a monochrome monitor and a dot matrix printer. On that computer I learned to write programs in Apple BASIC, Logo, and did simple animation in Br&#248;derbund Fantavision. I played King&rsquo;s Quest, Karateka, Montezuma's Revenge and Project Space Station games and even copied a version of Snake out of a BYTE magazine.</p>
			<p>In 1994 I purchased my first Apple Macintosh computer; a Quadra 610 DOS Compatible (only 25,000 were ever manufactured). This computer had a second, Intel 486SX, CPU which allowed you run MS-DOS and Windows 3.1 on the same hardware as Mac OS 7.1. The DOS Compatiblity card could have it&rsquo;s own RAM card or share the RAM on the Macintosh logic board. (This was 1994 when the rule of thumb was $100 a megabyte (MB) for buying RAM.) Not having an extra $800 I opted to share the RAM on the Mac; this setting was stored in the PRAM, a non-volatile random access memory chip. If the DOS Card was assigned too much memory it could prevent the Mac from booting up; you then had to reset the PRAM to get the memory back from the DOS card. To reset the PRAM you had to hold down Command-Option-P-R. The only reason I learned this bit of arcane knowledge was because I had this weird hybrid computer.</p>
			<p><a href="tron.php" class="trailing_image"><img src="https://s3-us-west-1.amazonaws.com/chuckharper/images/identity_disc.jpg" alt="Read Chuck&rsquo;s Tron Conversation" title="Read Chuck&rsquo;s Tron Conversation" /></a>In August 1995 I interviewed with <a href="http://www.sonnettech.com" rel="external">Sonnet Technology</a> (a leading manufacturer of Macintosh upgrades). In the interview the CEO, Robert Farnsworth, asked me how to reset the PRAM. I told him and he offered me a job. He later said I was the only candidate he interviewed, out of dozens, who could answer that question. As the Technical Support Manager at Sonnet I answered customer support phone calls, approved warranty exchanges and returns, and authored installation instructions and technical documentation. In 1996 I created Sonnet's first web site in Adobe PageMill.</p>
			<p><a href="https://s3-us-west-1.amazonaws.com/chuckharper/images/chuck_pathway.jpg" rel="shadowbox[Mixed];width=480;height=480" class="leading_image"><img src="https://s3-us-west-1.amazonaws.com/chuckharper/images/chuck_pathway_thumb.jpg" alt="Chuck at Pathway Capital Management in 1996" title="Chuck at Pathway Capital Management in 1996" /></a>In August, 1997 I moved to <a href="http://www.foxstudios.com/" rel="external">20th Century Fox</a> where I initially got a job working as a Macintosh Field Tech. In September, 1998 I was offered a salary position with Fox Filmed Entertainment as a <em>Systems Analyst</em>. While working for Fox I got to meet lots of celebrities and Hollywood executives. I traded Filemaker Pro information with Academy Award winner Jon Landau, I fixed Harold Ramis&rsquo;s Powerbook, and travelled to Toronto to set up the X-Men production office.</p>
			<p>In February 1999 I began taking freelance clients on a limited basis providing web design and programming, video post-production, database design, and on-site technical support; working with clients like <a href="http://henson.com" rel="external">The Jim Henson Company</a>, <a href="http://aubreyco.com" rel="external">Aubrey &amp; Associates</a> and Foote, Cone &amp; Belding (now <a href="http://www.draftfcb.com" rel="external">DraftFCB</a>.)</p>
			<p>In August 2000 I started working for <a href="http://www.pathwaycapital.com/" rel="external">Pathway Capital Management</a> in Irvine, California as a Web Programmer. While at Pathway I learned PHP and rebuilt Pathway&rsquo;s private access, proprietary, private equity financial reporting web-based software suite. I was then cross trained in 4th Dimension, an obscure PASCAL based database language.</p>
			<p><a href="https://s3-us-west-1.amazonaws.com/chuckharper/images/chuck_aeg.jpg" rel="shadowbox[Mixed];width=480;height=480" class="trailing_image"><img src="https://s3-us-west-1.amazonaws.com/chuckharper/images/chuck_aeg_thumb.jpg" alt="Chuck at AEG Expo 2011" title="Chuck at AEG Expo 2011" /></a>In April 2007 I took a contract position at <a href="http://www.aeglive.com" rel="external">AEG Live</a> to rebuild their corporate website. Near the completion of the project I was offered a salary position with AEG Live as a <em>Web Developer</em> where I worked on all of AEG Live's web sites including tour sites for <a href="http://bonjovi.aeglive.com/" rel="external">Bon Jovi</a>, <a href="http://www.celineinvegas.com/" rel="external">Celine Dion</a>, and&nbsp;<a href="http://tinaturnerlive.com/" rel="external">Tina Turner</a>; and venue sites like <a href="http://1stbankcenter.com/" rel="external">1STBANK Center</a> and <a href="http://www.clubnokia.com" rel="external">Club Nokia</a>. In April 2009 I was part of the team that built the web site to announce <a href="http://www.michaeljacksonlive.com" rel="external">Michael Jackson&rsquo;s</a> return to the stage at the O2 in London. The traffic to the site during the presale was massive (6.2 million hits on announce day, 245,000 uniques). With the help of the server team our site stayed up and running as our associated vendor sites crashed under the traffic load.</p>
			<p><a href="https://s3-us-west-1.amazonaws.com/chuckharper/images/axs_digital.jpg" rel="shadowbox[Mixed];width=480;height=480" class="leading_image"><img src="https://s3-us-west-1.amazonaws.com/chuckharper/images/axs_digital_thumb.jpg" alt="Chuck at AEG Expo 2012" title="Chuck at AEG Expo 2012" /></a>In 2010 I was promoted to <em>Technical Producer</em> in the AEG Digital division of AEG Live&rsquo;s parent company <a href="http://www.aegworldwide.com" rel="external">AEG Worldwide</a> where I continued to work on websites for AEG properties like <a href="http://www.coachella.com" rel="external">Coachella</a> and&nbsp;the attempted NFL stadium <a href="http://www.farmersfield.com" rel="external">Farmers Field</a>.</p>
			<p>Then, in January 2012, I was transfered to the <em>AXS Digital</em> division of AEG Worldwide where I was on the launch team for <a href="http://axs.com" rel="external">AXS</a>; a new ticketing brand to replace Ticketmaster in all AEG owned venues.</p>
			<p><a href="https://s3-us-west-1.amazonaws.com/chuckharper/images/smg.jpg" rel="shadowbox[Mixed];width=561;height=480" class="trailing_image"><img src="https://s3-us-west-1.amazonaws.com/chuckharper/images/smg_thumb.jpg" alt="Chuck at SMG Office" title="Chuck at SMG Office" height="184" /></a>In September 2014 I accepted a position as Senior Software Developer at Shock Media Group in Costa Mesa, a startup incubator company, working with entrepreneur Peter Nguyen. At SMG I have been instrumental in building the technology behind many new business and websites including <a href="https://www.brandslip.com" rel="external">BrandSlip.com</a> and <a href="http://pushinnovationlive.com/" rel="external">Push Innovation Live</a>.</p>
		</div>
	</div></div>
	
	<?php include($_SERVER['DOCUMENT_ROOT'] . '/includes/footer_personal.php'); ?>
</body>
</html>
